name: 🤖 Auto update bundled & used icons
on:
  pull_request:
  workflow_dispatch:

jobs:
  bundling:
    if: ${{ !contains(github.head_ref , 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.66.4
      - uses: taiga-family/ci/actions/setup/variables@v1.66.4
      - uses: taiga-family/ci/actions/setup/node@v1.66.4
      - name: Copy flags from design tokens icons
        run: |
          rm -rf ./projects/icons/src/flags && mkdir -p ./projects/icons/src/flags
          cp -R ./node_modules/@taiga-ui/design-tokens/icons/flags/* ./projects/icons/src/flags
          npx prettier ./projects/icons/src/flags --write
      - name: Material icons
        run: |
          npx nx prebuild icons-material
          npx prettier ./projects/icons-material/src/* --write
          npx nx build icons-material
      - run: |
          npx nx prebuild icons
          npx prettier ./projects/icons/src/* --write
          npx nx build icons
          npx ts-node ./scripts/generate-used-icons.ts
          npx eslint ./projects/cdk/constants/used-icons.ts --fix || echo "no file matching"
          npx eslint ./projects/demo/used-icons.ts --fix || echo "no file matching"
          npx prettier ./projects/demo/used-icons.ts --write || echo "no file matching"
          npx prettier ./projects/cdk/constants/used-icons.ts --write || echo "no file matching"
      - uses: taiga-family/ci/actions/auto/push@v1.66.4
        with:
          message: icons have changed
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
